// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbFG-XuUxdwG3GbB-hcjfF8dFoRIJYdhI',
    appId: '1:703528893342:web:0762ff5bc2da45e7fbf48f',
    messagingSenderId: '703528893342',
    projectId: 'aayoapplication',
    authDomain: 'aayoapplication.firebaseapp.com',
    storageBucket: 'aayoapplication.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCClH9xy_YDsht6rXX3P3gn6Y_HdJNhEMc',
    appId: '1:703528893342:android:d6fb345ab5421051fbf48f',
    messagingSenderId: '703528893342',
    projectId: 'aayoapplication',
    storageBucket: 'aayoapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxNltXjx43JP63WKOP0zqzUV5-7pE7eA8',
    appId: '1:703528893342:ios:b2334ee15e671336fbf48f',
    messagingSenderId: '703528893342',
    projectId: 'aayoapplication',
    storageBucket: 'aayoapplication.firebasestorage.app',
    iosClientId: '703528893342-4t7r4l1do2lfmp61n805nur2tgos7qae.apps.googleusercontent.com',
    iosBundleId: 'com.example.aayo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxNltXjx43JP63WKOP0zqzUV5-7pE7eA8',
    appId: '1:703528893342:ios:b2334ee15e671336fbf48f',
    messagingSenderId: '703528893342',
    projectId: 'aayoapplication',
    storageBucket: 'aayoapplication.firebasestorage.app',
    iosClientId: '703528893342-4t7r4l1do2lfmp61n805nur2tgos7qae.apps.googleusercontent.com',
    iosBundleId: 'com.example.aayo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbFG-XuUxdwG3GbB-hcjfF8dFoRIJYdhI',
    appId: '1:703528893342:web:7a11a5265bdfc5a0fbf48f',
    messagingSenderId: '703528893342',
    projectId: 'aayoapplication',
    authDomain: 'aayoapplication.firebaseapp.com',
    storageBucket: 'aayoapplication.firebasestorage.app',
  );
}